name: Create PDFs from HTML files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: sh to_pdf.sh
      
    - uses: actions/upload-artifact@v2
    - name: Uplaod artifacts
      with:
        name: cv-pdfs
        path: out/

    - uses: c-hive/gha-remove-artifacts@v1
    - name: Remove old artifacts
      with:
        skip-recent: 5
